<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>ByteMsg233</AssemblyName>
    <RootNamespace>ByteMsg233</RootNamespace>
    <Version>1.0.1</Version>
    <RepositoryUrl>https://github.com/neko233-com/bytemsg233-csharp-unity</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Runtime/**/*.cs" />
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
